%YAML 1.0
---

# input_images_folder: "/data/ifremer/victor_stereo_cam/acquisition_mire/2021-10-18-06-46-04_images/left_images/"
input_images_folder: "/home/maxime/Desktop/GP1"

# input_images_folder: "/data/ifremer/victor_stereo_cam/acquisition_mire/test_stereo_img/left_images"

dist_model: "radtan5" # (rad1, rad2, rad3, radtan4, radtan5, radtan8, kannalabrandt)

prior_fov: 70.0 # Prior FOV of the camera in degrees

target_type: "chessboard" # (chessboard / aprilgrid)

target_nb_rows: 7
target_nb_cols: 12

square_size: 0.05

debug: 0

use_autodiff: 1