%YAML 1.0
---

dist_model: "radtan4" # (rad1, rad2, rad3, radtan4, radtan5, radtan8, kannalabrandt)

prior_fov: 70.0 # Prior FOV of the camera in degrees

target_type: "aprilgrid" # (chessboard / aprilgrid)

target_nb_rows: 5
target_nb_cols: 8

tag_size: 0.06
tag_space: 0.25

debug: 0